import * as cloud from './cloud.js';
import {games,getGame,getSave} from './play-store.js';
import {safeMetadata} from './cloud-core.js';
import {ask} from './confirm-ui.js';
export async function installCloudPanel(refresh){
 const panel=document.createElement('section');panel.className='cloud-panel';panel.innerHTML=`<div class="eyebrow">PRIVATE CLOUD / เล่นต่อข้ามเครื่อง</div><h2>บัญชีและเซฟของคุณ</h2><p id="cloudMessage" role="status">กำลังตรวจบัญชี…</p><form id="cloudForm"><label>อีเมลบัญชีเล่นเกม<input name="email" type="email" autocomplete="username" required></label><label>รหัสผ่านบัญชีเล่นเกม<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">เข้าสู่ระบบ</button><p class="fine">ใช้บัญชีจาก Authentication ของ Supabase ไม่ใช่รหัส Database • การเข้าสู่ระบบจำไว้เฉพาะแท็บนี้ ไม่บันทึกรหัสผ่าน</p></form><div id="cloudActions" hidden><label class="check"><input id="cloudIncludeRom" type="checkbox"> เก็บไฟล์เกมและปกใน Cloud ส่วนตัวด้วย เพื่อเปิดอีกเครื่องแล้วเล่นได้เลย (ใช้พื้นที่/โควตาดาวน์โหลด)</label><div class="tools"><button id="cloudUpload" class="primary">เชื่อม / ซิงค์คลังในเครื่องขึ้น Cloud</button><button id="cloudRefresh">รีเฟรช Cloud</button><button id="cloudLogout">ออกจากบัญชี</button></div><p class="fine">เปิดเชื่อมครั้งแรกด้วยปุ่มด้านบน หลังจากนั้นเกมที่เชื่อมจะส่งเซฟทุก 60 วินาทีและตอนบันทึกออก ต้องรอข้อความ “ซิงค์ Cloud แล้ว” ก่อนสลับเครื่อง • หากไม่ได้เก็บ ROM ให้เพิ่มไฟล์เกมเดิมในอีกเครื่องหนึ่งครั้ง</p><div id="cloudGames"></div></div>`;
 document.querySelector('main').prepend(panel);const $=id=>panel.querySelector('#'+id);let busy=false;
 const message=t=>$('cloudMessage').textContent=t;
 async function run(fn){if(busy)return;busy=true;panel.querySelectorAll('button,input').forEach(e=>e.disabled=true);try{await fn();}catch(e){message(e.message);SG.toast(e.message);}finally{busy=false;panel.querySelectorAll('button,input').forEach(e=>e.disabled=false);}}
 async function render(){await cloud.ready;const u=cloud.user();$('cloudForm').hidden=!!u;$('cloudActions').hidden=!u;if(!u){message('ยังไม่เข้าสู่ระบบ • เซฟเดิมในเครื่องยังอยู่');await refresh();return;}
 message('เข้าสู่ระบบ: '+u.email+' • กำลังอ่านคลัง Cloud');const rows=await cloud.listCloud();$('cloudGames').replaceChildren();
 for(const row of rows){const m=safeMetadata(row.metadata),item=document.createElement('div');item.className='cloud-game';const label=document.createElement('p');label.textContent=m.title+' · Cloud รุ่น '+row.revision+' · '+new Date(row.updated_at).toLocaleString('th-TH');const play=document.createElement('button');play.textContent='▷ เล่นต่อ';play.onclick=()=>run(async()=>{let g=await getGame(row.game_id);if(!g||!g.cloudOwner){const exists=await getSave(row.game_id);if(exists&&!await ask('ดึงเซฟ Cloud แทนเซฟเครื่องนี้? จะดาวน์โหลดสำรองเซฟเดิมให้ก่อน'))return;g=await cloud.restoreGame(row.game_id,{replace:!!exists});}cloud.requireOwner(g);location.href='play.html?game='+row.game_id;});
 const pull=document.createElement('button');pull.textContent='ดึงเซฟ Cloud';pull.onclick=()=>run(async()=>{if(!await ask('แทนที่เซฟเกมนี้ในเครื่องด้วย Cloud ล่าสุด? หากมีเซฟในเครื่องจะดาวน์โหลดสำรองให้ก่อน ไม่เขียนทับเซฟ Cloud'))return;await cloud.restoreGame(row.game_id,{replace:true});await refresh();message('ดึง Cloud แล้ว • กดเล่นต่อได้เลย');});
 const backup=document.createElement('button');backup.textContent='สำรองเซฟในเครื่อง';backup.onclick=()=>run(()=>cloud.downloadLocalSave(row.game_id));item.append(label,play,pull,backup);$('cloudGames').append(item);}
 message('บัญชี '+u.email+' · พบ '+rows.length+' เกมบน Cloud');await refresh();}
 $('cloudForm').onsubmit=e=>{e.preventDefault();const email=e.currentTarget.elements.email.value.trim(),password=e.currentTarget.elements.password.value;e.currentTarget.elements.password.value='';run(async()=>{await cloud.login(email,password);await render();});};
 $('cloudLogout').onclick=()=>run(async()=>{await cloud.logout();await render();});
 $('cloudRefresh').onclick=()=>run(render);
 $('cloudUpload').onclick=()=>run(async()=>{const includeRom=$('cloudIncludeRom').checked,u=cloud.user();const list=(await games()).filter(g=>!g.cloudOwner||g.cloudOwner===u.id);if(!list.length)throw Error('เพิ่มเกมในเครื่องก่อน');let count=0;const failures=[];for(const g of list){message('กำลังซิงค์ '+g.name);try{await cloud.pushGame(g.id,{includeRom,adopt:true});count++;}catch(e){failures.push(g.name+': '+e.message);}}await render();message('ซิงค์สำเร็จ '+count+' เกม'+(failures.length?' • '+failures.join(' / '):' • อีกเครื่องล็อกอินบัญชีเดียวกันแล้วกดเล่นต่อได้'));});
 await run(render);return panel;
}
