import {TYPES,MATCHUPS} from './type-chart-data.js';
const names=['ปกติ','ต่อสู้','บิน','พิษ','ดิน','หิน','แมลง','ผี','เหล็ก','ไฟ','น้ำ','หญ้า','ไฟฟ้า','พลังจิต','น้ำแข็ง','มังกร','มืด','แฟรี่'];
const layout=document.querySelector('.play-layout');layout.querySelector('aside').classList.add('journey-side');
const aside=document.createElement('aside');aside.className='battle-reference';aside.innerHTML='<section class="play-card"><div class="eyebrow">BATTLE REFERENCE</div><h2>ตารางธาตุ</h2><label>ธาตุท่าโจมตี<select id="attackType"></select></label><label>ธาตุเป้าหมาย<select id="defendType"></select></label><label>ธาตุที่สอง (ถ้ามี)<select id="defendType2"><option value="">ไม่มี</option></select></label><output id="typeMultiplier" aria-live="polite"></output><p class="fine">อ้างอิงซอร์ส SoulGold ที่แนบ • ไม่รวม Ability, ไอเทม และสภาพสนาม • เกมเก่า/แฮ็กอื่นอาจต่างกัน</p><details><summary>ท่านี้โจมตีแต่ละธาตุ</summary><table class="matchup-table"><caption>ธาตุท่าโจมตี → ธาตุป้องกัน</caption><tbody id="matchupRows"></tbody></table></details></section>';
layout.prepend(aside);for(const id of ['attackType','defendType','defendType2']){const select=aside.querySelector('#'+id);TYPES.forEach((t,i)=>{const option=document.createElement('option');option.value=t;option.textContent=names[i]+' · '+t;select.append(option);});select.onchange=render;}
aside.querySelector('#attackType').value='FIRE';aside.querySelector('#defendType').value='GRASS';
function render(){const attack=aside.querySelector('#attackType').value,first=aside.querySelector('#defendType').value,second=aside.querySelector('#defendType2').value;
 const multiplier=MATCHUPS[attack][TYPES.indexOf(first)]*(second&&second!==first?MATCHUPS[attack][TYPES.indexOf(second)]:1);const out=aside.querySelector('#typeMultiplier');out.textContent=multiplier+'× '+(multiplier===0?'ไม่มีผล':multiplier>1?'ได้เปรียบ':multiplier<1?'เสียเปรียบ':'ปกติ');out.dataset.effect=multiplier>1?'strong':multiplier<1?'weak':'normal';
 const body=aside.querySelector('#matchupRows');body.replaceChildren();TYPES.forEach((t,i)=>{const tr=document.createElement('tr'),th=document.createElement('th'),td=document.createElement('td');th.scope='row';th.textContent=names[i];td.textContent=MATCHUPS[attack][i]+'×';tr.append(th,td);body.append(tr);});}
render();
